# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cendekia
email: hello@cendekiapp.com
description: >- # this means to ignore newlines until "baseurl:"
  A developer's journal documenting the process of building projects from scratch,
  sharing technical challenges, and tracking progress through a visual timeline.
baseurl: "" # the subpath of your site, e.g. /blogs
url: "https://cendekiapp.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cendekiapp
github_username: cendekia
linkedin_username: cendekiapp

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default front matter for collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blogs/:year/:month/:day/:title/
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      permalink: /projects/:title/
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json
  - docs/
  - .github/
  - LICENSE
  - CONTRIBUTING.md
  - .nojekyll
